### ISSUE TITLE
método insertar

### ISSUE THREAD

**Issue by DianaVertizdelValle** [mvalentinuz/TP1-AyED#2]
https://github.com/mvalentinuz/TP1-AyED/blob/08b7f396cd04e4c4340000f3ad35ddfc343c49eb/TAD/modulos/LDE.py#L74

**Comment by DianaVertizdelValle** [comment]
En este caso se debe utilizar la cola de la LDE, no debe llamarse al método anexar porque el elemento insertado queda en la posición anteúltima. Modificar esto

**Comment by mvalentinuz** [comment]
> En este caso se debe utilizar la cola de la LDE, no debe llamarse al método anexar porque el elemento insertado queda en la posición anteúltima. Modificar esto

Disculpe profesora, no entiendo esta corrección. Cuando testeo tal caso, el dato queda en el último lugar como debería, ya que la posición es el contador(tamaño)-1 a razón de que el primer elemento está en la posición cero. Además, el método anexar actualiza la referencia de cola, por lo que no entiendo por qué quedaría en la posición anteúltima.
